#!/bin/sh

cd "$(dirname "$0")" || exit
directory="./rofi"

files_rofi=$(find "$directory" -type f)
# files_scripts=$(find . -maxdepth 1 -type f -not -name '*.code-workspace')

delim='>'
get_lines() {
	for f in $files_rofi; do
		printf '%s %s%s\n' "$(basename "$f")" "$delim" "$(readlink -f "$f")"
	done
}

choice=$(get_lines | column -t | rofi -dmenu -i -mesg "$(shell_motd)" -p "Rofi Scripts")

# If nothing was chosen
[ -z "$choice" ] && exit

ch=$(echo "$choice" | cut -d "$delim" -f2)

"$ch" ||
	notify-send "'$ch' exited with error code $?"
