#!/bin/sh
# Start ssh agent if needed

export SSH_AUTH_SOCK="$HOME/.ssh/agent_socket"

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
	rm -f "$SSH_AUTH_SOCK"
fi

if [ ! -S "$SSH_AUTH_SOCK" ]; then
	eval "$(ssh-agent -a "$SSH_AUTH_SOCK" 2> /dev/null)"
	# ssh-add "$HOME"/.ssh/id_rsa
fi
